### ISSUE TITLE
Exporter will crash during sqlagent communication when using multiple column query 

### ISSUE THREAD

**Issue by dwburrill** [chop-dbhi/prometheus-sql#33]
## Description
The exporter will panic if there is a communication issue with the **dbhi/sql-agent**, when using a multi-column query.

## Steps to Reproduce
(Note: I am using docker containers in my environment.)

1. Create a config file similar to the following:
```
defaults:
  data-source: mssql-ds
  query-interval: 15s
  query-timeout: 2s
  query-value-on-error: -1

# Defined data sources
data-sources:
  mssql-ds:
    driver: mssql
    properties:
      host: 1.2.3.4
      port: 1234
      user: readonly_user
      password: 'readonly_password'
      database: mycooldb
```
2. Create a query file similar to the following:
```
- product_version:
    sql: >
        select top 1 build_number, version from product_version order by timestamp desc;

    # this is the main metric.  version will be exposed as a label
    data-field: build_number
```
3. Start the **dbhi/sql-agent** container
4. Start the **prometheus-sql** container
5. Once the prometheus-sql service calls the query successfully at least once, stop the **dbhi/sql-agent** container

## Actual Results
The next time prometheus-sql tries to run the query it will cause a panic.  See console log below:
```
2017/10/17 15:18:46 prometheus-sql starting up...
2017/10/17 15:18:46 Load config from file [prometheus-sql.yml]
2017/10/17 15:18:46 Load queries from file [queries.yml]
2017/10/17 15:18:46 * Listening on 0.0.0.0:8080...
Registering metric product_version with facets {"version":"3.1"}
[product_version] 2017/10/17 15:18:47 Fetch took 131.09459ms
[product_version] 2017/10/17 15:19:02 Fetch took 10.630444ms
[product_version] 2017/10/17 15:19:17 Fetch took 12.868919ms
[product_version] 2017/10/17 15:19:32 Fetch took 6.1882ms
Registering metric product_version with facets {}
panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "query_result_product_version", help: "Result of an SQL query", constLabels: {}, variableLabels: []} has different label names or a different help string
goroutine 8 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420012900, 0xc4200e6ea0, 0x1, 0x1)
        /go/src/github.com/prometheus/client_golang/prometheus/registry.go:354 +0x92
github.com/prometheus/client_golang/prometheus.MustRegister(0xc4200e6ea0, 0x1, 0x1)
        /go/src/github.com/prometheus/client_golang/prometheus/registry.go:153 +0x53
main.(*QueryResult).registerMetric(0xc4200e6790, 0xc420126cf0, 0xc420047b58, 0x0)
        /go/src/app/set.go:47 +0x666
main.(*QueryResult).SetMetrics(0xc4200e6790, 0xc420047d38, 0x1, 0x1, 0xc420086ea0, 0xc420086ea0, 0x946c70)
        /go/src/app/set.go:101 +0x425
main.(*Worker).SetMetrics(0xc4200d3c00, 0xc420047d38, 0x1, 0x1)
        /go/src/app/worker.go:40 +0x51
main.(*Worker).Fetch(0xc4200d3c00, 0x7ffc63129f5a, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/app/worker.go:90 +0x69e
main.(*Worker).Start.func1()
        /go/src/app/worker.go:124 +0x45
main.(*Worker).Start(0xc4200d3c00, 0x7ffc63129f5a, 0x14)
        /go/src/app/worker.go:143 +0x182
created by main.main
        /go/src/app/main.go:93 +0x7f8
```
## Expected Behaviour
The back off sequence should kick in instead of causing the exporter to panic and die.

## Workaround
Options:
1. Do not use multi column queries.
2. If you are using a docker container add an automatic restart option. E.g.:
```
docker run \
  --detach \
  --name prom-sql \
  --hostname promsql \
  --volume ~/sql-config.yml:/prometheus-sql.yml:z \
  --volume ~/sql-queries.yml:/queries.yml:z \
  --network promnet \
  --restart unless-stopped  \
dbhi/prometheus-sql -config prometheus-sql.yml -service http://sqlagent:5000
```
3. Do not set "query-value-on-error".  I had this originally set with a value of -1. By removing this, I no longer got the panic.  But more importantly, it wasn't setting a result of -1 which really screwed me up. because I was using a counter.  My sql results was then recording results, like 10, 20, 30, -1, 50 which when turned into a gauge, made incorrect results, e.g. 10, 10, 10, -31, 51, etc...

**Comment by haxorof** [comment]
Believe this is fixed by implementation done for #54. Reopen this if you still experience this issue.
