### ISSUE TITLE
Not able to retrieve more than 1K results per query

### ISSUE THREAD

**Issue by arnaudlemaignen** [chop-dbhi/prometheus-sql#50]
I am using this excellent exporter that works perfectly on a small Oracle DB.
But when I am trying to execute the same queries on huge DB with more 1K results then I am getting a panic mode '**duplicate metrics collector registration attempted**' using latest prometheus-sql code.

the query is long to fetch but that's OK (more or less same timing as in sqlplus)
`[states_new] 2018/09/18 14:29:59 Fetch took 11m57.264920312s`

but when registering the data it is breaking the whole app if more than 1K query results.
```
Registering metric states_new{"name":"MediumUnit2","vendor":"Cuchi"}
Registering metric states_new{"name":"MediumUnit","vendor":"Suchi"}
panic: duplicate metrics collector registration attempted
       panic: duplicate metrics collector registration attempted
goroutine 22 [running]:
app/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc4201c8400, 0xc4207e4800, 0x1, 0x1)
        /go/src/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:404 +0x9e
app/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc4207e4800, 0x1, 0x1)
        /go/src/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
main.(*QueryResult).RegisterMetrics.func1(0xc420738410, 0x50, 0x91f280, 0xc42015de80)
        /go/src/app/set.go:158 +0x13e
panic(0x7438c0, 0xc42087f160)
        /usr/local/go/src/runtime/panic.go:491 +0x283
app/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc4201c8400, 0xc4208748a0, 0x1, 0x1)
        /go/src/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:404 +0x9e
app/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc4208748a0, 0x1, 0x1)
        /go/src/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
main.(*QueryResult).RegisterMetrics.func1(0xc4204fce10, 0x4a, 0x91f280, 0xc4204d6400)
        /go/src/app/set.go:158 +0x13e
main.(*QueryResult).RegisterMetrics(0xc4201b5e10, 0xc4205cc5a0)
        /go/src/app/set.go:162 +0x27c
main.(*Worker).SetMetrics(0xc420398000, 0xc42058a000, 0x72d, 0x95e)
        /go/src/app/worker.go:46 +0xf0
main.(*Worker).Fetch(0xc420398000, 0x7ffe18e51a18, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/app/worker.go:117 +0x900
main.(*Worker).Start.func1()
        /go/src/app/worker.go:124 +0x45
main.(*Worker).Start(0xc420398000, 0x7ffe18e51a18, 0x29)
        /go/src/app/worker.go:131 +0x77
created by main.main
        /go/src/app/main.go:93 +0x70e

```

I tried many things like setting large interval and timeout in config.yml
```
  query-interval: 2400s
  query-timeout: 2400s
```

and also to scrape with really long timeout in Prometheus
```
- job_name: prometheus-sql
  scrape_interval: 40m
  scrape_timeout: 2300s
  metrics_path: /metrics
```
I also checked mem, cpu usage and there is no bottleneck on that end

**Comment by haxorof** [comment]
If this is still relevant for you then please try latest version which recently was built that fixes and issue that have similar stacktrace.

**Comment by haxorof** [comment]
Create new issue if you still have the problem in latest version.
